### ISSUE TITLE
Support for IDA 7

### ISSUE THREAD

**Issue by securisec** [Brandon-Everhart/AngryIDA#2]
Maybe support for IDA 7?

**Comment by Ektoplasma** [comment]
I tried on IDA 7. It worked like a charm for the needs I had.

**Comment by securisec** [comment]
@Ektoplasma @Brandon-Everhart @mrchisel14 i keep getting a UnboundLocalError: local variable 'argv1' referenced before assignment. Trying this on a mac... have you faced a similar issue?

**Comment by Ektoplasma** [comment]
@securisec yes, but it still works somehow.
